import fs from 'node:fs';
import path from 'node:path';
import { packIngredientIcons, getIngredientImagesDir } from '../ingredientIconPacker.js';

const FULL_GERMAN_TRANSLATIONS: Record<string, string> = {
  'aprikosensauce_von_frischen_fruechten': 'apricot_sauce_fresh',
  'aprikosensauce_von_getrockneten_fruechten': 'apricot_sauce_dried',
  'ascorbinsaeure': 'ascorbic_acid',
  'barsch_muellerinart': 'perch_meuniere',
  'batate_suesskartoffel': 'sweet_potato',
  'biersuppe_gesuesst': 'sweetened_beer_soup',
  'blaetterteig': 'puff_pastry',
  'blaetterteig_eifrei': 'egg_free_puff_pastry',
  'bluetenhonig': 'blossom_honey',
  'blumenkohl_gedaempft': 'steamed_cauliflower',
  'bohne_gruen': 'green_bean',
  'bouillon_bruehe_suppe': 'broth',
  'bratapfel_gefuellt_gebacken': 'baked_apple',
  'bratoel_frittieroel': 'frying_oil',
  'broetchen_glutenfrei': 'gluten_free_roll',
  'brotaufstrich_ei_kraeuter': 'egg_herb_spread',
  'buttermilch_dressing_fuer_salat': 'buttermilk_dressing',
  'citronensaeure_zitronensaeure': 'citric_acid',
  'curry_gewuerzketchup': 'curry_ketchup',
  'dinkelbroetchen': 'spelt_roll',
  'dinkelvollkornbroetchen': 'whole_grain_spelt_roll',
  'disteloel_safloroel': 'safflower_oil',
  'doener_kebab': 'doner_kebab',
  'doener_vegetarisch': 'vegetarian_doner',
  'eberesche_suess': 'rowanberry',
  'eiweissbroetchen_proteinbroetchen': 'protein_roll',
  'erbse_gruen': 'green_pea',
  'erdnussoel': 'peanut_oil',
  'erdnuss_geroestet': 'roasted_peanut',
  'essigsaeure_60': 'acetic_acid',
  'fischleberoel_lebertran': 'cod_liver_oil',
  'fischstaebchen': 'fish_fingers',
  'fleisch_bouillon_bruehe_suppe': 'meat_broth',
  'forelle_geraeuchert': 'smoked_trout',
  'forelle_muellerinart': 'trout_meuniere',
  'fraenkische_mehlkloesse': 'flour_dumplings',
  'frankfurter_gruene_kraeutersauce': 'green_herb_sauce',
  'fruchtmischung_ungesuesst': 'unsweetened_fruit_mix',
  'fruchtsaftgetraenk_apfel': 'apple_juice_drink',
  'fruehlingszwiebel_lauchzwiebel': 'spring_onion',
  'gemueseamaranth_gebraten_ohne_fett': 'fried_amaranth',
  'gemueseamaranth_raw': 'amaranth_leaves_raw',
  'gemueseamaranth_steamed': 'steamed_amaranth_leaves',
  'gemueseartischocke_kardone': 'artichoke',
  'gemuesebruehe': 'vegetable_broth',
  'gemuesecremesuppe_instantpulver': 'vegetable_cream_soup_powder',
  'gemuesefenchel_gebacken': 'baked_fennel',
  'gemuesefenchel_gebraten_ohne_fett': 'roasted_fennel',
  'gemuesefenchel_raw': 'fennel_raw',
  'gemuesefenchel_steamed': 'steamed_fennel',
  'gemuesemischung_asiatische_art': 'asian_vegetable_mix',
  'gemuesemischung_erbsen_karotten': 'peas_and_carrots_mix',
  'gemuesemischung_kaisergemuese': 'imperial_vegetable_mix',
  'gemuesepaprika_gelb': 'yellow_bell_pepper',
  'gemuesepaprika_gruen': 'green_bell_pepper',
  'gemuesepaprika_rot': 'red_bell_pepper',
  'gemuesesaft_aus_gurke': 'cucumber_juice',
  'gemuesesaft_aus_karotte_moehre': 'carrot_juice',
  'gemuesesaft_aus_knollensellerie': 'celery_juice',
  'gemuesesaft_aus_rote_ruebe_rote_bete': 'beetroot_juice',
  'gemuesesaft_aus_sauerkraut': 'sauerkraut_juice',
  'gemuesesaft_aus_speisezwiebel': 'onion_juice',
  'gemuesesaft_aus_spinat': 'spinach_juice',
  'gemuesesauce_von_bechamelsauce': 'vegetable_bechamel_sauce',
  'gemuesesauce_von_heller_weisser_grundsauce': 'vegetable_white_sauce',
  'gemuese_bouillon_bruehe_suppe': 'vegetable_broth',
  'getraenkepulver_kakaohaltig': 'cocoa_drink_powder',
  'gewuerzsalz_kraeutersalz': 'seasoned_salt',
  'glasnudeln_aus_mungbohnenstaerke': 'glass_noodles',
  'gruene_eiersauce_von_heller_weisser_grundsauce': 'green_egg_sauce',
  'gruenkernmehlsuppe': 'spelt_grain_soup',
  'gruenkern_vollkornmehl': 'green_spelt_flour',
  'gruenkohl_gebraten_ohne_fett': 'roasted_kale',
  'gruenkohl_gedaempft': 'steamed_kale',
  'gruenkohl_raw': 'kale_raw',
  'gruenkohl_steamed': 'kale_steamed',
  'gruentee': 'green_tea',
  'gurke_gesaeuert': 'pickled_cucumber',
  'haferbroetchen': 'oat_roll',
  'hagebuttensauce_aus_konfituere': 'rosehip_sauce',
  'halloumi_grillkaese': 'halloumi_cheese',
  'hanfoel': 'hemp_seed_oil',
  'haselnussoel': 'hazelnut_oil',
  'hefeteig_fuer_pizza_pizzateig': 'pizza_dough',
  'hefeteig_gesuesst': 'sweet_yeast_dough',
  'hefe_flocken_naehrhefe': 'nutritional_yeast_flakes',
  'heringssauce_aus_kraeutersauce_von_heller_weisser_grundsauce': 'herring_sauce',
  'hollaendische_sauce_einfach': 'hollandaise_sauce',
  'huehnerbruehe': 'chicken_broth',
  'huehnerei_eigelb': 'egg_yolk',
  'huehnerei_eiklar': 'egg_white',
  'huehnerei_raw': 'egg',
  'huehnerfett': 'chicken_fat',
  'huehner_bouillon_bruehe_suppe': 'chicken_broth',
  'kabeljaufilet_gefuellt': 'stuffed_cod_fillet',
  'kaisergemuese_steamed': 'steamed_imperial_vegetables',
  'kakaopulver_schwach_entoelt': 'dutch_cocoa_powder',
  'kakaopulver_stark_entoelt': 'natural_cocoa_powder',
  'kalbsruecken_gebraten_im_ofen': 'roasted_veal_saddle',
  'kapern_gesaeuert': 'pickled_capers',
  'karotten_moehren': 'carrots',
  'karotte_moehre': 'carrot',
  'kasseler_ruecken_gebraten_im_ofen': 'roasted_smoked_pork_loin',
  'knaeckebrot_glutenfrei': 'gluten_free_crispbread',
  'koehler_seelachs': 'coalfish',
  'koerniger_frischkaese_10_fett_i_tr': 'cottage_cheese',
  'kohlrueben_steckrueben': 'rutabagas',
  'kohlruebe_steckruebe': 'rutabaga',
  'kokosfett_gehaertet': 'hydrogenated_coconut_fat',
  'kokosoel': 'coconut_oil',
  'kokosoel_desodoriert': 'refined_coconut_oil',
  'konfituere_extra': 'extra_jam',
  'kraeuteressig': 'herb_vinegar',
  'kraeutersauce_von_bechamelsauce': 'herb_bechamel_sauce',
  'kraeutersauce_von_heller_weisser_grundsauce': 'herb_white_sauce',
  'kuemmelsauce_von_heller_weisser_grundsauce': 'caraway_sauce',
  'kuerbiskern': 'pumpkin_seed',
  'kuerbiskernoel': 'pumpkin_seed_oil',
  'kuerbis_gebacken': 'baked_pumpkin',
  'kuerbis_hokkaido': 'hokkaido_pumpkin',
  'kuerbis_pumpkin': 'pumpkin',
  'lachs_geraeuchert': 'smoked_salmon',
  'lammruecken_gebraten_im_ofen': 'roasted_lamb_saddle',
  'laugengebaeck': 'pretzel_pastry',
  'leinoel': 'flaxseed_oil',
  'loewenzahn_raw': 'dandelion_greens_raw',
  'maiskeimoel': 'corn_oil',
  'mais_staerke': 'cornstarch',
  'makrele_geraeuchert': 'smoked_mackerel',
  'mandeldrink_ungesuesst': 'almond_milk_unsweetened',
  'mandeloel': 'almond_oil',
  'mandel_suess': 'sweet_almonds',
  'mehlmischung_fuer_brot_glutenfrei': 'gluten_free_bread_flour_mix',
  'mehlmischung_fuer_kuchen_glutenfrei': 'gluten_free_cake_flour_mix',
  'mehlpuefferchen_fried': 'fried_flour_fritters',
  'mehrkornbroetchen': 'multigrain_roll',
  'mehrkornvollkornknaeckebrot': 'multigrain_crispbread',
  'mohnoel': 'poppy_seed_oil',
  'neuseelaender_spinat_gebraten_ohne_fett': 'roasted_warrigal_greens',
  'neuseelaender_spinat_raw': 'warrigal_greens_raw',
  'neuseelaender_spinat_steamed': 'steamed_warrigal_greens',
  'nitritpoekelsalz': 'curing_salt',
  'nitritpoekelsalz_jodiert': 'iodized_curing_salt',
  'nori_blatt_geroestet': 'toasted_nori_sheet',
  'nusshoernchen': 'nut_crescent_pastry',
  'palmfett_gehaertet': 'hydrogenated_palm_fat',
  'palmfett_palmoel': 'palm_oil',
  'palmkernfett_palmkernoel': 'palm_kernel_oil',
  'paniermehl_semmelbroesel_semmelmehl': 'breadcrumbs',
  'pfefferschote_gruen': 'green_chili_pepper',
  'pfeilwurzelmehl_marantastaerke': 'arrowroot_flour',
  'pirogue_with_cured_pork_loin_chop': 'pierogi_with_pork',
  'pistazie_geroestet_ohne_fett': 'roasted_pistachios',
  'pute_gefuellt': 'stuffed_turkey',
  'qualitaetsschaumwein': 'sparkling_wine',
  'rapsoelmargarine_vollfett': 'rapeseed_oil_margarine',
  'rapsoel_rueboel': 'rapeseed_oil',
  'reis_staerke': 'rice_starch',
  'roemischer_salat_romanasalat': 'romaine_lettuce',
  'roestzwiebeln': 'fried_onions',
  'roggenbroetchen': 'rye_roll',
  'roggenknaeckebrot': 'rye_crispbread',
  'roggenvollkornbroetchen': 'whole_grain_rye_roll',
  'roggenvollkornknaeckebrot': 'whole_grain_rye_crispbread',
  'rosinenbroetchen': 'raisin_roll',
  'rote_ruebe_rote_bete': 'beetroot',
  'rotweinsauce_suess': 'sweet_red_wine_sauce',
  'sahnesauce_suess': 'sweet_cream_sauce',
  'sahne_dressing_fuer_salat': 'cream_salad_dressing',
  'sahne_kaesesauce': 'cream_cheese_sauce',
  'sauce_hollandaise_hollaendische_sauce': 'hollandaise_sauce',
  'sauerampfer_steamed': 'steamed_sorrel',
  'sauerbraten_marinated_beef_roast': 'marinated_beef_roast',
  'sauerkirsche_steamed': 'steamed_sour_cherry',
  'sauerkraut_canned': 'canned_sauerkraut',
  'sauerkraut_drained': 'drained_sauerkraut',
  'sauerkraut_salad': 'sauerkraut_salad',
  'saure_sahne_dressing_fuer_salat': 'sour_cream_salad_dressing',
  'schmelzkaese_schnittfest': 'processed_cheese',
  'schnittsalat_pfluecksalat': 'leaf_lettuce',
  'schokobroetchen': 'chocolate_brioche_roll',
  'seelachsfilet_gedaempft': 'steamed_pollock_fillet',
  'seelachsfilet_muellerinart': 'pollock_fillet_meuniere',
  'seezunge_muellerinart': 'sole_meuniere',
  'senf_honig_dressing_fuer_salat': 'honey_mustard_dressing',
  'senf_suess': 'sweet_mustard',
  'sesamoel': 'sesame_oil',
  'sojadrink_ungesuesst': 'unsweetened_soy_milk',
  'sojaoel': 'soybean_oil',
  'spargel_gedaempft': 'steamed_asparagus',
  'stielmus_ruebstiel': 'turnip_tops',
  'suesskartoffeln_und_broccoli_steamed': 'sweet_potatoes_and_broccoli',
  'suesskirsche_dried': 'dried_sweet_cherries',
  'suesskirsche_raw': 'sweet_cherry',
  'suesskirsche_steamed': 'steamed_sweet_cherries',
  'suesskirschsaft': 'sweet_cherry_juice',
  'suessrahmbutter': 'sweet_cream_butter',
  'suppengruen_suppenkraut': 'soup_greens',
  'tapioka_tapiokastaerke': 'tapioca_starch',
  'thueringer_mohnkuchen': 'poppy_seed_cake',
  'thueringer_obstkuchen': 'fruit_sheet_cake',
  'tomatensauce_aus_frischen_tomaten_und_frischkaese': 'tomato_cream_cheese_sauce',
  'tomaten_passiert_tomatenpueree': 'tomato_passata',
  'traubenkernoel': 'grape_seed_oil',
  'trueffel_dried': 'dried_truffle',
  'trueffel_gebraten_ohne_fett': 'roasted_truffle',
  'trueffel_raw': 'truffle_raw',
  'trueffel_steamed': 'steamed_truffle',
  'vollkornbroetchen': 'whole_grain_roll',
  'vollkornhefeteig_fuer_pizza_vollkornpizzateig': 'whole_grain_pizza_dough',
  'vollkornhefeteig_suess_gebacken': 'baked_sweet_whole_grain_yeast_dough',
  'vollkornhefeteig_suess_raw': 'sweet_whole_grain_yeast_dough_raw',
  'walnussoel': 'walnut_oil',
  'weinsuppe_gesuesst': 'sweet_wine_soup',
  'weisse_ruebe_wasserruebe_herbstruebe': 'white_turnip',
  'weizenbaguettebroetchen': 'wheat_baguette_roll',
  'weizenbroetchen': 'wheat_roll',
  'weizenkeimoel': 'wheat_germ_oil',
  'weizenmischbroetchen': 'mixed_wheat_roll',
  'weizenvollkornbroetchen': 'whole_grain_wheat_roll',
  'weizen_staerke': 'wheat_starch',
  'westfaelischer_panhas': 'panhas_pork_terrine',
  'wiener_hoernchen': 'croissant',
  'wiener_wuerstchen': 'wiener_sausage',
  'zanderfilet_muellerinart': 'pike_perch_meuniere',
  'zartbitter_halbbitter_kuvertuere': 'dark_chocolate_couverture',
};

async function main() {
  const iconsDir = getIngredientImagesDir();
  console.log(`\n==================================================`);
  console.log(`🧹 Full Purge of Remaining German Icon Names`);
  console.log(`==================================================`);
  console.log(`📂 Icons Directory: ${iconsDir}`);

  const files = fs.readdirSync(iconsDir).filter(f => f.endsWith('.webp'));
  console.log(`📦 Scanning ${files.length} icon files...`);

  let renamedCount = 0;
  let deletedCount = 0;

  for (const [germanKey, englishKey] of Object.entries(FULL_GERMAN_TRANSLATIONS)) {
    const germanFile = `${germanKey}.webp`;
    const englishFile = `${englishKey}.webp`;

    const germanPath = path.join(iconsDir, germanFile);
    const englishPath = path.join(iconsDir, englishFile);

    if (fs.existsSync(germanPath)) {
      if (!fs.existsSync(englishPath)) {
        fs.copyFileSync(germanPath, englishPath);
        renamedCount++;
      }
      fs.unlinkSync(germanPath);
      deletedCount++;
    }
  }

  const remaining = fs.readdirSync(iconsDir).filter(f => f.endsWith('.webp'));
  console.log(`\n✨ Successfully deleted ${deletedCount} German files.`);
  console.log(`✨ Created/Ensured ${renamedCount} English files.`);
  console.log(`📦 Remaining clean English icons: ${remaining.length}`);

  // Re-pack zip
  console.log(`\n🗜️  Re-packing ingredient-icons.zip...`);
  const zipRes = packIngredientIcons({ verbose: true });
  console.log(`📦 Zip updated: ${zipRes.fileCount} files (${zipRes.zipSizeMb} MB) in ${zipRes.durationMs}ms`);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
