/**
 * Database Restore Script (API-based, no psql or Docker required)
 *
 * Restores tables from a JSON backup file generated by backupDatabase.ts.
 *
 * Usage:
 *   npx tsx src/scripts/restoreDatabase.ts --dev [--file path/to/backup.json] [--confirm]
 *   npx tsx src/scripts/restoreDatabase.ts --prod [--file path/to/backup.json] [--confirm]
 */

import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

const isProd = process.argv.includes('--prod');
const isConfirmed = process.argv.includes('--confirm');
const envFile = isProd ? '.env.production' : '.env';
const envPath = path.resolve(process.cwd(), envFile);

if (!fs.existsSync(envPath)) {
  console.error(`❌ Environment file not found: ${envFile}`);
  process.exit(1);
}

const envConfig = dotenv.parse(fs.readFileSync(envPath, 'utf8'));
const supabaseUrl = envConfig.SUPABASE_URL;
const supabaseKey = envConfig.SUPABASE_SECRET_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error(`❌ SUPABASE_URL or SUPABASE_SECRET_KEY missing in ${envFile}`);
  process.exit(1);
}

const client = createClient(supabaseUrl, supabaseKey);

// Topological ordering to respect foreign key constraints during restore
const TABLE_DEPENDENCY_ORDER = [
  'global_settings',
  'gemini_logs',
  'feedback',
  'push_tokens',
  'app_bundles',
  'food_items',
  'profiles',
  'friendships',
  'jobs',
  'jobs_legacy',
  'recipes',
  'user_recipes',
  'collections',
  'recipe_collections',
  'cook_events',
  'point_ledger',
  'user_stats',
  'user_badges',
  'ingredient_mappings',
  'pantry_items',
  'shopping_list',
  'meal_plans',
  'meal_plan_entries',
  'notification_log',
];

function getSpecifiedOrLatestBackup(): string | null {
  const fileArgIndex = process.argv.indexOf('--file');
  if (fileArgIndex !== -1 && process.argv[fileArgIndex + 1]) {
    const specified = path.resolve(process.cwd(), process.argv[fileArgIndex + 1]);
    if (fs.existsSync(specified)) return specified;
    console.error(`❌ Specified backup file not found: ${specified}`);
    process.exit(1);
  }

  const backupsDir = path.resolve(process.cwd(), 'backups');
  if (!fs.existsSync(backupsDir)) return null;

  const targetPrefix = isProd ? 'backup_prod_' : 'backup_dev_';
  const matchingFiles = fs
    .readdirSync(backupsDir)
    .filter(f => f.startsWith(targetPrefix) && f.endsWith('.json'))
    .map(f => ({ name: f, time: fs.statSync(path.join(backupsDir, f)).mtimeMs }))
    .sort((a, b) => b.time - a.time);

  return matchingFiles.length > 0 ? path.join(backupsDir, matchingFiles[0].name) : null;
}

async function restoreTable(
  tableName: string,
  rows: unknown[],
  isDryRun: boolean
): Promise<{ success: boolean; inserted: number; error?: string }> {
  if (rows.length === 0) {
    return { success: true, inserted: 0 };
  }

  if (isDryRun) {
    return { success: true, inserted: rows.length };
  }

  const chunkSize = 100;
  let inserted = 0;

  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const { error } = await client.from(tableName).upsert(chunk);

    if (error) {
      return { success: false, inserted, error: error.message };
    }
    inserted += chunk.length;
  }

  return { success: true, inserted };
}

async function run(): Promise<void> {
  const backupFile = getSpecifiedOrLatestBackup();
  if (!backupFile) {
    console.error(`❌ No backup file found in backups/ directory.`);
    console.error(`Please provide one with --file <path> or run a backup first.`);
    process.exit(1);
  }

  const host = new URL(supabaseUrl).host;
  const isDryRun = !isConfirmed;

  console.log(`============================================================`);
  console.log(`Supabase Database Restore`);
  console.log(`Target:      ${isProd ? 'PRODUCTION' : 'DEVELOPMENT'} (${host})`);
  console.log(`File:        ${backupFile}`);
  console.log(`Mode:        ${isDryRun ? 'DRY-RUN (Pass --confirm to execute)' : 'LIVE RESTORE'}`);
  console.log(`============================================================\n`);

  if (isProd && !isDryRun) {
    console.log(`⚠️ ATTENTION: RESTORING TO PRODUCTION DATABASE (${host})`);
  }

  const rawJson = fs.readFileSync(backupFile, 'utf8');
  const backup = JSON.parse(rawJson) as {
    metadata: { target: string; host: string; timestamp: string };
    data: Record<string, unknown[]>;
  };

  const backupTables = Object.keys(backup.data || {});
  console.log(`Backup metadata: created on ${backup.metadata.timestamp} for ${backup.metadata.target} (${backup.metadata.host})`);
  console.log(`Found ${backupTables.length} tables in backup file.\n`);

  // Order tables by dependency order, append any remaining unknown tables at the end
  const sortedTables = [
    ...TABLE_DEPENDENCY_ORDER.filter(t => backupTables.includes(t)),
    ...backupTables.filter(t => !TABLE_DEPENDENCY_ORDER.includes(t)),
  ];

  let totalRestored = 0;
  let totalErrors = 0;

  for (const table of sortedTables) {
    const rows = backup.data[table] || [];
    process.stdout.write(`Restoring ${table.padEnd(22)} (${rows.length.toString().padStart(5)} rows)... `);

    const result = await restoreTable(table, rows, isDryRun);
    if (result.success) {
      console.log(`✓ ${isDryRun ? 'dry-run ok' : `${result.inserted} rows upserted`}`);
      totalRestored += result.inserted;
    } else {
      console.log(`❌ ERROR: ${result.error}`);
      totalErrors++;
    }
  }

  console.log(`\n============================================================`);
  if (isDryRun) {
    console.log(`🔍 DRY-RUN COMPLETED: All ${totalRestored} rows across ${sortedTables.length} tables verified.`);
    console.log(`To actually write to the database, run:`);
    console.log(`  npx tsx src/scripts/restoreDatabase.ts ${isProd ? '--prod' : '--dev'} --confirm`);
  } else {
    console.log(`✅ RESTORE COMPLETED!`);
    console.log(`  Total rows restored: ${totalRestored}`);
    console.log(`  Table errors:        ${totalErrors}`);
  }
  console.log(`============================================================`);
}

const isDirectExecution =
  process.argv[1] &&
  (process.argv[1].endsWith('restoreDatabase.ts') ||
    process.argv[1].endsWith('restoreDatabase.js'));

if (isDirectExecution) {
  run().catch(err => {
    console.error('Fatal restore error:', err);
    process.exit(1);
  });
}
