import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

const backendEnvBase = path.join(rootDir, 'backend', '.env');
const backendEnvDev = path.join(rootDir, 'backend', '.env.development');
const backendEnvProd = path.join(rootDir, 'backend', '.env.production');
const backendEnvLocal = path.join(rootDir, 'backend', '.env.local');
const frontendEnvDevLocal = path.join(rootDir, 'frontend', '.env.development.local');
const frontendEnvLocal = path.join(rootDir, 'frontend', '.env.local');

const command = process.argv[2]?.toLowerCase();

function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const result = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      result[match[1].trim()] = match[2].trim();
    }
  }
  return result;
}

function getDevEnv() {
  const base = parseEnv(backendEnvBase);
  const dev = fs.existsSync(backendEnvDev) ? parseEnv(backendEnvDev) : {};
  return { ...base, ...dev };
}

function getProdEnv() {
  const base = parseEnv(backendEnvBase);
  const prod = fs.existsSync(backendEnvProd) ? parseEnv(backendEnvProd) : {};
  return { ...base, ...prod };
}

function updateEnvKeys(filePath, updates) {
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, 'utf8');
  for (const [key, val] of Object.entries(updates)) {
    const regex = new RegExp(`^${key}=.*$`, 'm');
    if (regex.test(content)) {
      if (val !== null && val !== undefined) {
        content = content.replace(regex, `${key}=${val}`);
      } else {
        content = content.replace(new RegExp(`^${key}=.*\\r?\\n?`, 'm'), '');
      }
    } else if (val !== null && val !== undefined) {
      content += `\n${key}=${val}\n`;
    }
  }
  fs.writeFileSync(filePath, content, 'utf8');
}

function stopActiveDevServers() {
  try {
    if (process.platform === 'win32') {
      execSync(
        'powershell -Command "Get-NetTCPConnection -LocalPort 3000, 5173 -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique | ForEach-Object { Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue }"',
        { stdio: 'ignore' }
      );
    }
  } catch {
    // Ignore errors if no processes were running
  }
}

function getActiveStatus() {
  const backendLocal = fs.existsSync(backendEnvLocal) ? parseEnv(backendEnvLocal) : null;
  const devEnv = getDevEnv();
  const frontendLocal = fs.existsSync(frontendEnvLocal) ? parseEnv(frontendEnvLocal) : null;
  const frontendDevLocal = fs.existsSync(frontendEnvDevLocal) ? parseEnv(frontendEnvDevLocal) : null;

  const backendHost = backendLocal?.SUPABASE_URL
    ? new URL(backendLocal.SUPABASE_URL).host
    : devEnv.SUPABASE_URL
      ? new URL(devEnv.SUPABASE_URL).host
      : 'unknown';

  const frontendHost = frontendDevLocal?.VITE_SUPABASE_URL
    ? new URL(frontendDevLocal.VITE_SUPABASE_URL).host
    : frontendLocal?.VITE_SUPABASE_URL
      ? new URL(frontendLocal.VITE_SUPABASE_URL).host
      : backendHost;

  const isProd = Boolean(backendLocal?.SUPABASE_URL);
  const isInSync = backendHost === frontendHost;

  return { isProd, backendHost, frontendHost, isInSync };
}

if (command === 'prod') {
  if (!fs.existsSync(backendEnvProd)) {
    console.error('❌ Error: backend/.env.production not found!');
    process.exit(1);
  }

  const prodEnv = getProdEnv();
  const prodOverrides = parseEnv(backendEnvProd);
  if (!prodEnv.SUPABASE_URL || !prodEnv.SUPABASE_PUBLISHABLE_KEY || !prodEnv.SUPABASE_SECRET_KEY) {
    console.error('❌ Error: Required Supabase keys missing in backend/.env.production');
    process.exit(1);
  }

  // 1. Write backend/.env.local (overrides with all production variables)
  let backendContent = `# Local override pointing to PRODUCTION database & services (generated by npm run use:prod)\n`;
  for (const [key, val] of Object.entries(prodOverrides)) {
    backendContent += `${key}=${val}\n`;
  }
  fs.writeFileSync(backendEnvLocal, backendContent, 'utf8');

  // 2. Write frontend/.env.development.local (overrides Auth & Supabase for frontend in dev mode)
  const frontendContent = `# Local override pointing to PRODUCTION database (generated by npm run use:prod)
VITE_SUPABASE_URL=${prodEnv.SUPABASE_URL}
VITE_SUPABASE_PUBLISHABLE_KEY=${prodEnv.SUPABASE_PUBLISHABLE_KEY}
`;
  fs.writeFileSync(frontendEnvDevLocal, frontendContent, 'utf8');

  // 3. Keep frontend/.env.local in sync so Vite never uses stale DEV overrides
  updateEnvKeys(frontendEnvLocal, {
    VITE_SUPABASE_URL: prodEnv.SUPABASE_URL,
    VITE_SUPABASE_PUBLISHABLE_KEY: prodEnv.SUPABASE_PUBLISHABLE_KEY,
  });

  // Stop running servers on 3000 & 5173 so changes take immediate effect on restart
  stopActiveDevServers();

  const host = new URL(prodEnv.SUPABASE_URL).host;
  console.log('============================================================');
  console.log('🟢 SWITCHED LOCAL DEV TO: PRODUCTION DATABASE');
  console.log(`Database Host:    ${host}`);
  console.log(`Backend config:   backend/.env.local (active)`);
  console.log(`Frontend config:  frontend/.env.development.local & frontend/.env.local (active)`);
  console.log('');
  console.log('⚡ Active dev processes on ports 3000 & 5173 stopped (if any).');
  console.log('▶️  Run "npm run dev" to start dev servers against the PRODUCTION DB.');
  console.log('↩️  To switch back to dev DB: "npm run use:dev"');
  console.log('============================================================');
} else if (command === 'dev') {
  if (fs.existsSync(backendEnvLocal)) {
    fs.unlinkSync(backendEnvLocal);
  }
  if (fs.existsSync(frontendEnvDevLocal)) {
    fs.unlinkSync(frontendEnvDevLocal);
  }

  // Restore dev Supabase keys in frontend/.env.local
  const devEnv = getDevEnv();
  if (devEnv.SUPABASE_URL && devEnv.SUPABASE_PUBLISHABLE_KEY) {
    updateEnvKeys(frontendEnvLocal, {
      VITE_SUPABASE_URL: devEnv.SUPABASE_URL,
      VITE_SUPABASE_PUBLISHABLE_KEY: devEnv.SUPABASE_PUBLISHABLE_KEY,
    });
  }

  // Stop running servers on 3000 & 5173 so changes take immediate effect on restart
  stopActiveDevServers();

  const host = devEnv.SUPABASE_URL ? new URL(devEnv.SUPABASE_URL).host : 'unknown';

  console.log('============================================================');
  console.log('🔵 SWITCHED LOCAL DEV TO: DEVELOPMENT DATABASE');
  console.log(`Database Host:    ${host}`);
  console.log('Local production overrides removed.');
  console.log('');
  console.log('⚡ Active dev processes on ports 3000 & 5173 stopped (if any).');
  console.log('▶️  Run "npm run dev" to start dev servers against the DEVELOPMENT DB.');
  console.log('============================================================');
} else {
  // Status check
  const status = getActiveStatus();
  console.log('============================================================');
  console.log('Current Local Environment Target:');
  if (status.isProd) {
    console.log(`🟢 PRODUCTION DB (${status.backendHost})`);
  } else {
    console.log(`🔵 DEVELOPMENT DB (${status.backendHost})`);
  }
  console.log(`Backend Host:   ${status.backendHost}`);
  console.log(`Frontend Host:  ${status.frontendHost}`);

  if (!status.isInSync) {
    console.warn('⚠️  WARNING: Backend and Frontend are pointing to DIFFERENT databases!');
    console.warn('   Run "npm run use:prod" or "npm run use:dev" to re-synchronize them.');
  } else {
    console.log('✅ Backend and Frontend are in sync.');
  }

  console.log('');
  if (status.isProd) {
    console.log('To switch to dev DB:  npm run use:dev');
  } else {
    console.log('To switch to prod DB: npm run use:prod');
  }
  console.log('============================================================');
}
