import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

const backendEnvBase = path.join(rootDir, 'backend', '.env');
const backendEnvDev = path.join(rootDir, 'backend', '.env.development');
const backendEnvProd = path.join(rootDir, 'backend', '.env.production');
const backendEnvLocal = path.join(rootDir, 'backend', '.env.local');
const frontendEnvDevLocal = path.join(rootDir, 'frontend', '.env.development.local');
const frontendEnvLocal = path.join(rootDir, 'frontend', '.env.local');

const args = process.argv.slice(2);
const command = args[0]?.toLowerCase();
const isRemoteBackend = args.includes('--backend') || args.includes('-b') || command === 'prod:backend' || command === 'backend:prod';

function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const result = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      result[match[1].trim()] = match[2].trim();
    }
  }
  return result;
}

function getDevEnv() {
  const base = parseEnv(backendEnvBase);
  const dev = fs.existsSync(backendEnvDev) ? parseEnv(backendEnvDev) : {};
  return { ...base, ...dev };
}

function getProdEnv() {
  const base = parseEnv(backendEnvBase);
  const prod = fs.existsSync(backendEnvProd) ? parseEnv(backendEnvProd) : {};
  return { ...base, ...prod };
}

function getProdBackendUrl() {
  const prodFrontend = parseEnv(path.join(rootDir, 'frontend', '.env.production'));
  return prodFrontend.VITE_API_BASE_URL || 'https://cookbook-production-8769.up.railway.app';
}

function getDbHost(url) {
  try {
    if (!url) return 'none';
    const parsed = new URL(url);
    return parsed.host;
  } catch {
    return 'unknown';
  }
}

function updateEnvKeys(filePath, updates) {
  if (!fs.existsSync(filePath)) return;
  let content = fs.readFileSync(filePath, 'utf8');
  for (const [key, val] of Object.entries(updates)) {
    const regex = new RegExp(`^${key}=.*$`, 'm');
    if (regex.test(content)) {
      if (val !== null && val !== undefined && val !== '') {
        content = content.replace(regex, `${key}=${val}`);
      } else {
        content = content.replace(new RegExp(`^${key}=.*\\r?\\n?`, 'm'), '');
      }
    } else if (val !== null && val !== undefined && val !== '') {
      content += `\n${key}=${val}\n`;
    }
  }
  fs.writeFileSync(filePath, content, 'utf8');
}

function stopActiveDevServers() {
  try {
    if (process.platform === 'win32') {
      execSync(
        'powershell -Command "Get-NetTCPConnection -LocalPort 3000, 5173 -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess -Unique | ForEach-Object { Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue }"',
        { stdio: 'ignore' }
      );
    }
  } catch {
    // Ignore errors if no processes were running
  }
}

function getActiveStatus() {
  const backendLocal = fs.existsSync(backendEnvLocal) ? parseEnv(backendEnvLocal) : null;
  const devEnv = getDevEnv();
  const frontendLocal = fs.existsSync(frontendEnvLocal) ? parseEnv(frontendEnvLocal) : null;
  const frontendDevLocal = fs.existsSync(frontendEnvDevLocal) ? parseEnv(frontendEnvDevLocal) : null;

  const backendHost = getDbHost(backendLocal?.DATABASE_URL || devEnv.DATABASE_URL);
  const remoteBackendUrl = frontendDevLocal?.VITE_API_BASE_URL || frontendLocal?.VITE_API_BASE_URL || null;
  const isHostedBackend = Boolean(remoteBackendUrl);

  const isProd = Boolean(backendLocal?.DATABASE_URL) || isHostedBackend;

  return { isProd, isHostedBackend, remoteBackendUrl, backendHost };
}

if (command === 'prod' || command === 'prod:backend' || command === 'backend:prod') {
  if (!fs.existsSync(backendEnvProd)) {
    console.error('❌ Error: backend/.env.production not found!');
    process.exit(1);
  }

  const prodEnv = getProdEnv();
  const prodOverrides = parseEnv(backendEnvProd);
  if (!prodEnv.DATABASE_URL) {
    console.error('❌ Error: DATABASE_URL missing in backend/.env.production');
    process.exit(1);
  }

  const prodBackendUrl = getProdBackendUrl();

  // 1. Write backend/.env.local (overrides with all production variables)
  let backendContent = `# Local override pointing to PRODUCTION database & services (generated by npm run use:prod)\n`;
  for (const [key, val] of Object.entries(prodOverrides)) {
    backendContent += `${key}=${val}\n`;
  }
  fs.writeFileSync(backendEnvLocal, backendContent, 'utf8');

  // 2. Write frontend/.env.development.local if hosted backend requested
  if (isRemoteBackend) {
    let frontendContent = `# Local override pointing to HOSTED PRODUCTION BACKEND (generated by npm run use:prod:backend)\n`;
    frontendContent += `VITE_API_BASE_URL=${prodBackendUrl}\n`;
    fs.writeFileSync(frontendEnvDevLocal, frontendContent, 'utf8');
    updateEnvKeys(frontendEnvLocal, { VITE_API_BASE_URL: prodBackendUrl });
  } else {
    if (fs.existsSync(frontendEnvDevLocal)) {
      fs.unlinkSync(frontendEnvDevLocal);
    }
    updateEnvKeys(frontendEnvLocal, { VITE_API_BASE_URL: null });
  }

  // Stop running servers on 3000 & 5173 so changes take immediate effect on restart
  stopActiveDevServers();

  const host = getDbHost(prodEnv.DATABASE_URL);
  console.log('============================================================');
  if (isRemoteBackend) {
    console.log('🟢 SWITCHED LOCAL DEV TO: HOSTED PRODUCTION BACKEND & DB');
    console.log(`Backend API:      ${prodBackendUrl} (hosted on Railway)`);
    console.log(`Database Host:    ${host}`);
    console.log(`Frontend config:  frontend/.env.development.local & frontend/.env.local (active)`);
    console.log(`Backend config:   backend/.env.local (active)`);
    console.log('');
    console.log('ℹ️  Frontend communicates directly with the live Railway Production Backend.');
  } else {
    console.log('🟢 SWITCHED LOCAL DEV TO: PRODUCTION DATABASE (Local Backend)');
    console.log(`Database Host:    ${host}`);
    console.log(`Backend API:      http://localhost:3000 (local dev server)`);
    console.log(`Backend config:   backend/.env.local (active)`);
    console.log('');
    console.log('ℹ️  Backend runs LOCALLY on port 3000 against the production DB.');
    console.log('   To point frontend to hosted production backend: "npm run use:prod:backend"');
  }
  console.log('');
  console.log('⚡ Active dev processes on ports 3000 & 5173 stopped (if any).');
  console.log('▶️  Run "npm run dev" to start dev servers.');
  console.log('↩️  To switch back to dev: "npm run use:dev"');
  console.log('============================================================');
} else if (command === 'dev') {
  if (fs.existsSync(backendEnvLocal)) {
    fs.unlinkSync(backendEnvLocal);
  }
  if (fs.existsSync(frontendEnvDevLocal)) {
    fs.unlinkSync(frontendEnvDevLocal);
  }

  updateEnvKeys(frontendEnvLocal, {
    VITE_API_BASE_URL: null,
  });

  // Stop running servers on 3000 & 5173 so changes take immediate effect on restart
  stopActiveDevServers();

  const devEnv = getDevEnv();
  const host = getDbHost(devEnv.DATABASE_URL);

  console.log('============================================================');
  console.log('🔵 SWITCHED LOCAL DEV TO: DEVELOPMENT DATABASE (Local Backend)');
  console.log(`Database Host:    ${host}`);
  console.log(`Backend API:      http://localhost:3000 (local dev proxy)`);
  console.log('Local production overrides removed.');
  console.log('');
  console.log('⚡ Active dev processes on ports 3000 & 5173 stopped (if any).');
  console.log('▶️  Run "npm run dev" to start dev servers against the DEVELOPMENT DB.');
  console.log('============================================================');
} else {
  // Status check
  const status = getActiveStatus();
  console.log('============================================================');
  console.log('Current Local Environment Target:');
  if (status.isHostedBackend) {
    console.log(`🟢 HOSTED PRODUCTION BACKEND (${status.remoteBackendUrl})`);
    console.log(`Backend API:    ${status.remoteBackendUrl} (hosted on Railway)`);
  } else if (status.isProd) {
    console.log(`🟢 PRODUCTION DB (Local Backend on port 3000)`);
    console.log(`Backend API:    http://localhost:3000 (local dev server)`);
  } else {
    console.log(`🔵 DEVELOPMENT DB (Local Backend on port 3000)`);
    console.log(`Backend API:    http://localhost:3000 (local dev proxy)`);
  }
  console.log(`Database Host:  ${status.backendHost}`);
  console.log('');
  if (status.isHostedBackend) {
    console.log('To use local backend with prod DB: npm run use:prod');
    console.log('To switch back to dev DB:          npm run use:dev');
  } else if (status.isProd) {
    console.log('To use hosted prod backend:        npm run use:prod:backend');
    console.log('To switch back to dev DB:          npm run use:dev');
  } else {
    console.log('To switch to prod DB:              npm run use:prod');
    console.log('To use hosted prod backend:        npm run use:prod:backend');
  }
  console.log('============================================================');
}
