import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

const backendEnvProd = path.join(rootDir, 'backend', '.env.production');
const backendEnvDev = path.join(rootDir, 'backend', '.env');
const backendEnvLocal = path.join(rootDir, 'backend', '.env.local');
const frontendEnvDevLocal = path.join(rootDir, 'frontend', '.env.development.local');

const command = process.argv[2]?.toLowerCase();

function parseEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const result = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      result[match[1].trim()] = match[2].trim();
    }
  }
  return result;
}

function getActiveStatus() {
  if (fs.existsSync(backendEnvLocal)) {
    const local = parseEnv(backendEnvLocal);
    const host = local.SUPABASE_URL ? new URL(local.SUPABASE_URL).host : 'unknown';
    return { isProd: true, host, envFile: backendEnvLocal };
  }
  const dev = parseEnv(backendEnvDev);
  const host = dev.SUPABASE_URL ? new URL(dev.SUPABASE_URL).host : 'unknown';
  return { isProd: false, host, envFile: backendEnvDev };
}

if (command === 'prod') {
  if (!fs.existsSync(backendEnvProd)) {
    console.error('❌ Error: backend/.env.production not found!');
    process.exit(1);
  }

  const prodEnv = parseEnv(backendEnvProd);
  if (!prodEnv.SUPABASE_URL || !prodEnv.SUPABASE_PUBLISHABLE_KEY || !prodEnv.SUPABASE_SECRET_KEY) {
    console.error('❌ Error: Required Supabase keys missing in backend/.env.production');
    process.exit(1);
  }

  // 1. Write backend/.env.local (overrides only DB connection for backend)
  const backendContent = `# Local override pointing to PRODUCTION database (generated by npm run use:prod)
SUPABASE_URL=${prodEnv.SUPABASE_URL}
SUPABASE_PUBLISHABLE_KEY=${prodEnv.SUPABASE_PUBLISHABLE_KEY}
SUPABASE_SECRET_KEY=${prodEnv.SUPABASE_SECRET_KEY}
`;
  fs.writeFileSync(backendEnvLocal, backendContent, 'utf8');

  // 2. Write frontend/.env.development.local (overrides Auth & Supabase for frontend)
  const frontendContent = `# Local override pointing to PRODUCTION database (generated by npm run use:prod)
VITE_SUPABASE_URL=${prodEnv.SUPABASE_URL}
VITE_SUPABASE_PUBLISHABLE_KEY=${prodEnv.SUPABASE_PUBLISHABLE_KEY}
`;
  fs.writeFileSync(frontendEnvDevLocal, frontendContent, 'utf8');

  const host = new URL(prodEnv.SUPABASE_URL).host;
  console.log('============================================================');
  console.log('🟢 SWITCHED LOCAL DEV TO: PRODUCTION DATABASE');
  console.log(`Database Host:  ${host}`);
  console.log(`Backend config: backend/.env.local (active)`);
  console.log(`Frontend config: frontend/.env.development.local (active)`);
  console.log('');
  console.log('Run "npm run dev" to develop against the PRODUCTION DB.');
  console.log('To switch back to dev DB: "npm run use:dev"');
  console.log('============================================================');
} else if (command === 'dev') {
  let removed = false;
  if (fs.existsSync(backendEnvLocal)) {
    fs.unlinkSync(backendEnvLocal);
    removed = true;
  }
  if (fs.existsSync(frontendEnvDevLocal)) {
    fs.unlinkSync(frontendEnvDevLocal);
    removed = true;
  }

  const devEnv = parseEnv(backendEnvDev);
  const host = devEnv.SUPABASE_URL ? new URL(devEnv.SUPABASE_URL).host : 'unknown';

  console.log('============================================================');
  console.log('🔵 SWITCHED LOCAL DEV TO: DEVELOPMENT DATABASE');
  console.log(`Database Host:  ${host}`);
  console.log('Local production overrides removed.');
  console.log('');
  console.log('Run "npm run dev" to develop against the DEVELOPMENT DB.');
  console.log('============================================================');
} else {
  // Status check
  const status = getActiveStatus();
  console.log('============================================================');
  console.log('Current Local Environment Target:');
  if (status.isProd) {
    console.log(`🟢 PRODUCTION DB (${status.host})`);
    console.log('Local dev is currently connected to Production.');
    console.log('To switch to dev DB:  npm run use:dev');
  } else {
    console.log(`🔵 DEVELOPMENT DB (${status.host})`);
    console.log('Local dev is currently connected to Development.');
    console.log('To switch to prod DB: npm run use:prod');
  }
  console.log('============================================================');
}
