// Helpers for parsing inline ingredient and timer tags from step instructions.
// Step descriptions contain inline tags generated by Gemini:
// - Ingredients: `[word in text](ing:baseName)`
// - Timers: `[time text](timer:seconds)`

const INLINE_ING_REGEX = /\[([^\]]+)\]\(ing:([^)]+)\)/g;
const INLINE_TIMER_REGEX = /\[([^\]]+)\]\(timer:(\d+)\)/g;
const ALL_INLINE_TAGS_REGEX = /\[([^\]]+)\]\((?:ing|timer|temp):[^)]+\)/g;

export interface InlineIngredientMatch {
  wordInText: string;
  baseName: string;
}

export interface InlineTimerMatch {
  timeText: string;
  seconds: number;
}

/**
 * Extracts all inline ingredient tags `[word](ing:baseName)` present in a step description.
 */
export function extractInlineIngredientTags(text: string): InlineIngredientMatch[] {
  if (!text) return [];
  const matches: InlineIngredientMatch[] = [];
  const regex = new RegExp(INLINE_ING_REGEX);
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    matches.push({
      wordInText: match[1],
      baseName: match[2].trim(),
    });
  }

  return matches;
}

/**
 * Extracts all inline timer tags `[time text](timer:seconds)` present in a step description.
 */
export function extractInlineTimerTags(text: string): InlineTimerMatch[] {
  if (!text) return [];
  const matches: InlineTimerMatch[] = [];
  const regex = new RegExp(INLINE_TIMER_REGEX);
  let match: RegExpExecArray | null;

  while ((match = regex.exec(text)) !== null) {
    const timeText = match[1];
    // Filter out accidental temperature tags
    if (/°[CF]?|\b(?:grad|celsius|fahrenheit|umluft|oberhitze|unterhitze)\b/i.test(timeText)) {
      continue;
    }
    matches.push({
      timeText,
      seconds: parseInt(match[2], 10),
    });
  }

  return matches;
}

/**
 * Strips all inline `[word](ing:...)` and `[time](timer:...)` tags from a text string, returning plain text.
 */
export function stripInlineIngredientTags(text: string): string {
  if (!text) return '';
  return text.replace(ALL_INLINE_TAGS_REGEX, '$1');
}

/**
 * Language-neutral fallback for legacy recipes without inline tags:
 * Checks whether `text` mentions `term` as a standalone word.
 */
export function textMentionsTerm(term: string | undefined | null, text: string): boolean {
  if (!term || !text) return false;
  const trimmed = term.trim();
  if (trimmed.length < 2) return false;

  const escaped = trimmed.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
  const boundary = `[\\s.,:;!?()\\[\\]{}'"\\-\\/]`;

  try {
    const regex = new RegExp(`(?<=^|${boundary})${escaped}(?=$|${boundary})`, 'iu');
    return regex.test(text);
  } catch {
    return text.toLowerCase().includes(trimmed.toLowerCase());
  }
}
